"""Portas de persistência do contexto work."""

from __future__ import annotations

import uuid
from dataclasses import dataclass
from datetime import datetime
from typing import Protocol

from cadencia.work.domain.entities import Board, Project, Sprint, WorkItem


@dataclass(frozen=True)
class AssignmentRecord:
    id: uuid.UUID
    work_item_id: uuid.UUID
    sprint_id: uuid.UUID
    added_at: datetime
    removed_at: datetime | None


class ProjectRepository(Protocol):
    async def get(self, project_id: uuid.UUID, workspace_id: uuid.UUID) -> Project | None: ...
    async def list_for_workspace(self, workspace_id: uuid.UUID) -> list[Project]: ...
    async def key_exists(
        self, workspace_id: uuid.UUID, key: str, *, exclude_project_id: uuid.UUID | None = None
    ) -> bool: ...
    async def add(self, project: Project) -> None: ...
    async def save(self, project: Project) -> None: ...


class BoardRepository(Protocol):
    async def get(self, board_id: uuid.UUID) -> Board | None: ...
    async def get_by_project(self, project_id: uuid.UUID) -> Board | None: ...
    async def add(self, board: Board) -> None: ...
    async def save(self, board: Board) -> None: ...


class WorkItemRepository(Protocol):
    async def get(self, item_id: uuid.UUID) -> WorkItem | None: ...
    async def get_by_key(self, project_id: uuid.UUID, key: str) -> WorkItem | None: ...
    async def list_for_project(self, project_id: uuid.UUID) -> list[WorkItem]: ...
    async def list_for_sprint(self, sprint_id: uuid.UUID) -> list[WorkItem]: ...
    async def list_in_column(self, column_id: uuid.UUID) -> list[WorkItem]: ...
    async def count_in_column(
        self, column_id: uuid.UUID, *, exclude_item_id: uuid.UUID | None = None
    ) -> int: ...
    async def next_position(self, column_id: uuid.UUID) -> float: ...
    async def add(self, item: WorkItem) -> None: ...
    async def save(self, item: WorkItem) -> None: ...
    async def save_many(self, items: list[WorkItem]) -> None: ...


class SprintRepository(Protocol):
    async def get(self, sprint_id: uuid.UUID) -> Sprint | None: ...
    async def list_for_project(self, project_id: uuid.UUID) -> list[Sprint]: ...
    async def active_for_board(self, board_id: uuid.UUID) -> Sprint | None: ...
    async def count_assigned(self, sprint_id: uuid.UUID) -> int: ...
    async def add(self, sprint: Sprint) -> None: ...
    async def save(self, sprint: Sprint) -> None: ...


class AssignmentRepository(Protocol):
    async def add(self, record: AssignmentRecord) -> None: ...
    async def close_open_for_item(self, item_id: uuid.UUID, now: datetime) -> None: ...
    async def list_for_sprint(self, sprint_id: uuid.UUID) -> list[AssignmentRecord]: ...
    async def list_for_item(self, item_id: uuid.UUID) -> list[AssignmentRecord]: ...
